<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [ ]:

# Your code here


### 1.2 Named functions that don’t return

In [ ]:

# Your code here


### 1.3 Anonymous functions

In [ ]:

# Your code here


### 1.4 Optional arguments

In [ ]:

# Your code here


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

The following code works as expected despite not having an `else` statement. Please use a Markdown cell to explain why?

```
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
```

The `return` keyword causes Python to jump out of the function with the value stated after it (I.E. 'Hello [...] you!'), which is why even if there were an `else` statement after it, it would be ignored

## Exercise 2 :  Calculator functions

1. Create four `functions add(x, y)`, `subtract(x, y)`, `multiply(x, y)` and `divide(x, y)` that realise the operations `x+y`, `x-y`, `x*y` and `x/y` respectively.

For the division case, remember to add an `if` condition to admonish the division user by zero.
<p>You will have to use the function `exit()`<sup>23</sup> to force Python to stop.

2. Test your functions with the following NumPy arrays(!)<sup>24</sup>.

```
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
```

In [11]:
import numpy as np

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def add(x,y):
    return (x+y)
    
add(x,y)

array([100, 100, 100, 100, 100])

In [12]:
import numpy as np

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def subtract(x,y):
    return (x-y)
    
subtract(x,y)

array([-28, -32, -12,  52, -46])

In [13]:
import numpy as np

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def multiply(x,y):
    return (x*y)
    
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [1]:
import numpy as np

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def divide(x,y):
    if np.any(y!=0):
        return x/y
    else:
        return f'Dividing by zero is not allowed :('

for i in range(5):
    print(divide(x[i],y[i]))

0.5625
0.5151515151515151
0.7857142857142857
3.1666666666666665
0.3698630136986301


## Exercise 3 :  max_info() with NumPy

Create a function called `max_info(numbers)` that accepts a list and returns the maximum value and the index (i.e. location) of the maximum.

Base your code on the `np.max()` and `np.argmax()` functions of NumPy.

Test your function with the list:

```
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
```

In [ ]:
import numpy as np

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    return f'The maximum value is {np.max(numbers)} which is in position {np.argmax(numbers)+1}.'

max_info(numbers)